### ISSUE TITLE
Maybe it's more elegant to use the `grpc.Server.GracefulStop` API to close the `context` in `Get`?

### ISSUE THREAD

**Issue by zbysir** [teivah/onecontext#2]
I read the readme of the project and have some ideas to discuss with you. :)

According to my test, listen the global context expiration event in the outermost layer of the app and calling the `GracefulStop` API of grpc can also make the app exit accurately. I think the `context` expiration processing in `Get` should be handled by `grpc`, not us, do you think so?

**Comment by teivah** [comment]
The example I gave in the readme isn't about stopping the server.
